### ISSUE TITLE
Time to replace retiring spatial packages

### ISSUE THREAD

**Issue by rsbivand** [AndriSignorell/bfsMaps#2]
rgdal, rgeos and maptools will retire during 2023. As is explained in this presentation: https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf, package maintainers should aim to have replaced probably redundant dependencies on these packages by June 2023 (before the northern hemisphere tutorial season), and certainly by October 2023 when the packages will be archived. The presentation was recorded: https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1. Further details in blogs: https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html, and in tabulations on https://github.com/r-spatial/evolution.

maptools::unionSpatialPolygons() is similar to sf::aggregate(), rgdal::readOGR() to st::st_read(), and rgeos::gLength rgeos::readWKT have sf equivalents.

**Comment by AndriSignorell** [comment]
Thanks Roger for the reminder!
Yes, the task has been on my todo list for some time now and I will attack it soon.
Best, Andri

**Comment by rsbivand** [comment]
New blog published this week with added hints: https://r-spatial.org/r/2023/04/10/evolution3.html

**Comment by rsbivand** [comment]
And see https://r-spatial.org/r/2023/05/15/evolution4.html. The window of opportunity for dropping the three retiring packages is closing.

**Comment by AndriSignorell** [comment]
The transition has been made, I have been able to implement all functions with sf in the best possible way - and everything much easier, thank you for your invaluable work.
The new version has been published to CRAN today.

**Comment by rsbivand** [comment]
`1.99.3` checks OK for me, thanks!
